id: P004374
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG10000
  title: དཔལ་རྡོ་རྗེ་འཇིགས་བྱེད་སོགས་ཆོས་སྐྱོང་འགའི་སྒྲུབ་སྐོར།
  author: ''
  volumes:
    84c5f868c41b4be39ddbe9c9608255f9:
      image_group_id: I1KG10005
      title: ''
      volume_number: 1
      total_pages: 676
      base_file: v001.txt
