id: I2B7D3623
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T11:00:11+00:00'
last_modified: '2022-06-07T22:24:03.690977+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG10000
  title: དཔལ་རྡོ་རྗེ་འཇིགས་བྱེད་སོགས་ཆོས་སྐྱོང་འགའི་སྒྲུབ་སྐོར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    443A:
      image_group_id: I1KG10005
      title: ''
      total_pages: 676
      order: 1
      base_file: 443A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
